Finish Mobile Pull Request
Techcolony/Portfolio-setup pull request #2
Opened 2023-03-24 16:19 UTC by Techcolony

This is the Finish Mobile Pull Request to merge the finish-mobile-feature with the main branch

2023-03-24 16:59 UTC, algerina requested changes
Hi @Techcolony  ,

Great job so far! 
However, you still have minor issues to fix.

May I highlight the following: 
- [x] Your project looks awesome👏  ✔️ 
- [x] No Linter errors✔️ 


## STATUS: CHANGES REQUIRED ♻️ 
PLEASE: check the comments under the review

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

- [ Optional] The hamburger menu and the social media icons  are not displayed kindly add a `.` at the beginning of their links.

![port1](https://user-images.githubusercontent.com/53347966/227591414-808b7e54-4273-4bae-b0f4-d502721889e7.JPG)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-03-24 16:59 UTC, algerina commented on style.css
> +}
- [x] You did a great job however it is required to use display:grid on the main container of the work section.

2023-03-24 16:59 UTC, algerina commented on index.html
> +                            <h1>Tonic</h1>
- [x] It's recommended  to use only one h1 per page for SEO reasons, kindly change h1 to h2, h3, ... on all your work cards.

2023-03-24 16:59 UTC, algerina commented on index.html
> +                                <li><img src="icons-images/HTML.png">HTML</li>
- [x] It's required to use a section tag for the About section instead of a div.

2023-03-24 16:59 UTC, algerina commented on index.html
> +                            <h1 class="separator">Frameworks</h1>
- [x] Kindly change this h1 to another hx tag as requested previously.

2023-03-25 11:57 UTC, Techcolony commented on style.css
> +}
Thanks for this

2023-03-25 11:58 UTC, Techcolony commented on index.html
> +                            <h1 class="separator">Frameworks</h1>
ok, that's right.

2023-03-25 12:18 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Techcolony 

Your project is complete! Great job for taking out time to make the changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- figma design well followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀

![tufoin](https://media.giphy.com/media/l2YWBf0KFf6Kze6AM/giphy.gif) 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 12:33 UTC, merged